theme: jekyll-theme-minimal

logo: THF_Roundel_whitecentre.png

title: H Foundation REAL Testing 
description: "Resources and code: "

baseurl: 
url: 

# Google Analytics
# google_analytics: G-9WTK7S5JYD
